#include <assert.h>
#include <limits.h>
#include <math.h>
#include <stdbool.h>

#include "arithmos/number-theory/rational.h"

#define ASSERT_RATIONAL_EQ(r, n, d, s) \
    assert((r).numerator == (n) && (r).denominator == (d) && (r).sign == (s))

#define ASSERT_RATIONAL_INF(r, is_negative) \
    assert((r).denominator == 0 && (r).sign == (is_negative))

#define ASSERT_RATIONAL_NAN(r, is_negative) \
    assert(arithmos_rational_is_nan(&(r)) && (r).sign == (is_negative))

int main() {
    Arithmos_Rational r;

    arithmos_rational_init(&r);
    ASSERT_RATIONAL_EQ(r, 0, 1, false);

    arithmos_rational_from_ull(&r, 0, 5, false);
    ASSERT_RATIONAL_EQ(r, 0, 1, false);
    arithmos_rational_from_ull(&r, 0, 7, true);
    ASSERT_RATIONAL_EQ(r, 0, 1, true);
    arithmos_rational_from_ull(&r, 5, 0, true);
    ASSERT_RATIONAL_EQ(r, 1, 0, true);
    arithmos_rational_from_ull(&r, 0, 0, true);
    ASSERT_RATIONAL_NAN(r, true);
    arithmos_rational_from_ull(&r, 10, 20, true);
    ASSERT_RATIONAL_EQ(r, 1, 2, true);
    arithmos_rational_from_ull(&r, 3, 4, false);
    ASSERT_RATIONAL_EQ(r, 3, 4, false);
    arithmos_rational_from_ull(&r, 1000000000000ULL, 500000000000ULL, false);
    ASSERT_RATIONAL_EQ(r, 2, 1, false);
    arithmos_rational_from_ull(&r, 42, 1, true);
    ASSERT_RATIONAL_EQ(r, 42, 1, true);
    arithmos_rational_from_ull(&r, 1, 99, false);
    ASSERT_RATIONAL_EQ(r, 1, 99, false);
    arithmos_rational_from_ull(&r, 25, 25, true);
    ASSERT_RATIONAL_EQ(r, 1, 1, true);
    arithmos_rational_from_ull(&r, ULLONG_MAX, ULLONG_MAX, false);
    ASSERT_RATIONAL_EQ(r, 1, 1, false);

    Arithmos_Rational source, dest;

    arithmos_rational_from_ull(&source, 22, 7, false);
    arithmos_rational_copy(&dest, &source);
    ASSERT_RATIONAL_EQ(dest, 22, 7, false);
    arithmos_rational_from_ull(&source, 5, 9, true);
    arithmos_rational_copy(&dest, &source);
    ASSERT_RATIONAL_EQ(dest, 5, 9, true);
    source = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    arithmos_rational_copy(&dest, &source);
    ASSERT_RATIONAL_INF(dest, true);
    source = ARITHMOS_RATIONAL_POSITIVE_NAN;
    arithmos_rational_copy(&dest, &source);
    ASSERT_RATIONAL_NAN(dest, false);

    assert(arithmos_rational_is_zero(&r) == false);
    r = ARITHMOS_RATIONAL_POSITIVE_ZERO;
    assert(arithmos_rational_is_zero(&r) == true);
    r = ARITHMOS_RATIONAL_NEGATIVE_ZERO;
    assert(arithmos_rational_is_zero(&r) == true);

    assert(arithmos_rational_is_infinity(&r) == false);
    r = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    assert(arithmos_rational_is_infinity(&r) == true);
    r = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    assert(arithmos_rational_is_infinity(&r) == true);

    assert(arithmos_rational_is_nan(&r) == false);
    r = ARITHMOS_RATIONAL_POSITIVE_NAN;
    assert(arithmos_rational_is_nan(&r) == true);
    r = ARITHMOS_RATIONAL_NEGATIVE_NAN;
    assert(arithmos_rational_is_nan(&r) == true);

    Arithmos_Rational r1, r2;

    arithmos_rational_from_ull(&r1, 1, 2, false);
    arithmos_rational_from_ull(&r2, 2, 4, false);
    assert(arithmos_rational_compare(r1, r2) == 0);
    arithmos_rational_from_ull(&r1, 3, 4, false);
    arithmos_rational_from_ull(&r2, 3, 4, true);
    assert(arithmos_rational_compare(r1, r2) > 0);
    assert(arithmos_rational_compare(r2, r1) < 0);
    arithmos_rational_from_ull(&r1, 0, 5, false);
    arithmos_rational_from_ull(&r2, 0, 10, true);
    assert(arithmos_rational_compare(r1, r2) == 0);
    arithmos_rational_from_ull(&r1, 3, 5, false);
    arithmos_rational_from_ull(&r2, 2, 5, false);
    assert(arithmos_rational_compare(r1, r2) > 0);
    arithmos_rational_from_ull(&r1, 3, 5, true);
    arithmos_rational_from_ull(&r2, 2, 5, true);
    assert(arithmos_rational_compare(r1, r2) < 0);
    arithmos_rational_from_ull(&r1, 1, 0, false);
    arithmos_rational_from_ull(&r2, 1000, 1, false);
    assert(arithmos_rational_compare(r1, r2) > 0);
    arithmos_rational_from_ull(&r1, 1, 0, true);
    arithmos_rational_from_ull(&r2, 1000, 1, false);
    assert(arithmos_rational_compare(r1, r2) < 0);
    arithmos_rational_from_ull(&r1, 42, 0, false);
    arithmos_rational_from_ull(&r2, 99, 0, false);
    assert(arithmos_rational_compare(r1, r2) == 0);
    arithmos_rational_from_ull(&r1, 42, 0, true);
    arithmos_rational_from_ull(&r2, 99, 0, true);
    assert(arithmos_rational_compare(r1, r2) == 0);
    arithmos_rational_from_ull(&r1, 1, 0, false);
    arithmos_rational_from_ull(&r2, 1, 0, true);
    assert(arithmos_rational_compare(r1, r2) > 0);
    assert(arithmos_rational_compare(r2, r1) < 0);
    arithmos_rational_from_ull(&r1, 10, 20, true);
    arithmos_rational_from_ull(&r2, 1, 2, true);
    assert(arithmos_rational_compare(r1, r2) == 0);
    arithmos_rational_from_ull(&r1, 100000000000ULL, 300000000000ULL, false);
    arithmos_rational_from_ull(&r2, 1, 3, false);
    assert(arithmos_rational_compare(r1, r2) == 0);

    arithmos_rational_from_ull(&r1, 3, 4, false);
    arithmos_rational_from_ull(&r2, 6, 8, false);
    assert(arithmos_rational_equals(r1, r2));
    arithmos_rational_from_ull(&r1, 1, 2, true);
    arithmos_rational_from_ull(&r2, 2, 4, true);
    assert(arithmos_rational_equals(r1, r2));
    arithmos_rational_from_ull(&r1, 1, 2, false);
    arithmos_rational_from_ull(&r2, 2, 3, false);
    assert(!arithmos_rational_equals(r1, r2));
    arithmos_rational_from_ull(&r1, 3, 5, false);
    arithmos_rational_from_ull(&r2, 3, 5, true);
    assert(!arithmos_rational_equals(r1, r2));
    r1 = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    arithmos_rational_from_ull(&r2, 100, 0, false);
    assert(arithmos_rational_equals(r1, r2));
    r1 = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    r2 = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    assert(!arithmos_rational_equals(r1, r2));
    r1 = ARITHMOS_RATIONAL_POSITIVE_NAN;
    r2 = ARITHMOS_RATIONAL_POSITIVE_NAN;
    assert(!arithmos_rational_equals(r1, r2));

    arithmos_rational_from_ull(&r, 3, 5, false);
    arithmos_rational_abs(&r);
    ASSERT_RATIONAL_EQ(r, 3, 5, false);
    arithmos_rational_from_ull(&r, 7, 8, true);
    arithmos_rational_abs(&r);
    ASSERT_RATIONAL_EQ(r, 7, 8, false);
    r = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    arithmos_rational_abs(&r);
    ASSERT_RATIONAL_INF(r, false);
    r = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    arithmos_rational_abs(&r);
    ASSERT_RATIONAL_INF(r, false);
    r = ARITHMOS_RATIONAL_POSITIVE_NAN;
    arithmos_rational_abs(&r);
    ASSERT_RATIONAL_NAN(r, false);

    arithmos_rational_from_ull(&r, 3, 4, false);
    arithmos_rational_negate(&r);
    ASSERT_RATIONAL_EQ(r, 3, 4, true);
    arithmos_rational_from_ull(&r, 5, 6, true);
    arithmos_rational_negate(&r);
    ASSERT_RATIONAL_EQ(r, 5, 6, false);
    r = ARITHMOS_RATIONAL_POSITIVE_ZERO;
    arithmos_rational_negate(&r);
    ASSERT_RATIONAL_EQ(r, 0, 1, true);
    arithmos_rational_from_ull(&r, 0, 7, true);
    arithmos_rational_negate(&r);
    ASSERT_RATIONAL_EQ(r, 0, 1, false);
    r = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    arithmos_rational_negate(&r);
    ASSERT_RATIONAL_INF(r, true);
    r = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    arithmos_rational_negate(&r);
    ASSERT_RATIONAL_INF(r, false);
    r = ARITHMOS_RATIONAL_POSITIVE_NAN;
    arithmos_rational_negate(&r);
    ASSERT_RATIONAL_NAN(r, true);

    Arithmos_Rational result;
    bool overflow;

    r1 = ARITHMOS_RATIONAL_NEGATIVE_ZERO;
    r2 = ARITHMOS_RATIONAL_POSITIVE_ZERO;
    overflow = arithmos_rational_sum(r1, r2, &result);
    arithmos_rational_print(stderr, &result);
    ASSERT_RATIONAL_EQ(result, 0, 1, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 3, false);
    arithmos_rational_from_ull(&r2, 1, 6, false);
    overflow = arithmos_rational_sum(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 1, 2, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 2, true);
    arithmos_rational_from_ull(&r2, 1, 2, false);
    overflow = arithmos_rational_sum(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 0, 1, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 3, true);
    arithmos_rational_from_ull(&r2, 2, 3, true);
    overflow = arithmos_rational_sum(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 1, 1, true);
    assert(!overflow);
    r1 = ARITHMOS_RATIONAL_POSITIVE_NAN;
    arithmos_rational_from_ull(&r2, 5, 2, false);
    overflow = arithmos_rational_sum(r1, r2, &result);
    ASSERT_RATIONAL_NAN(result, false);
    r1 = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    r2 = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    overflow = arithmos_rational_sum(r1, r2, &result);
    ASSERT_RATIONAL_INF(result, false);
    r1 = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    r2 = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    overflow = arithmos_rational_sum(r1, r2, &result);
    ASSERT_RATIONAL_NAN(result, false);
    arithmos_rational_from_ull(&r1, ULLONG_MAX, 1, false);
    arithmos_rational_from_ull(&r2, ULLONG_MAX, 1, false);
    overflow = arithmos_rational_sum(r1, r2, &result);
    assert(overflow);

    arithmos_rational_from_ull(&r1, 3, 4, false);
    arithmos_rational_from_ull(&r2, 1, 4, false);
    overflow = arithmos_rational_difference(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 1, 2, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 2, false);
    arithmos_rational_from_ull(&r2, 3, 2, false);
    overflow = arithmos_rational_difference(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 1, 1, true);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 3, true);
    arithmos_rational_from_ull(&r2, 2, 3, false);
    overflow = arithmos_rational_difference(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 1, 1, true);
    assert(!overflow);
    r1 = ARITHMOS_RATIONAL_POSITIVE_NAN;
    arithmos_rational_from_ull(&r2, 1, 2, false);
    overflow = arithmos_rational_difference(r1, r2, &result);
    ASSERT_RATIONAL_NAN(result, false);
    r1 = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    r2 = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    overflow = arithmos_rational_difference(r1, r2, &result);
    ASSERT_RATIONAL_NAN(result, false);
    r1 = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    r2 = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    overflow = arithmos_rational_difference(r1, r2, &result);
    ASSERT_RATIONAL_INF(result, false);
    arithmos_rational_from_ull(&r1, ULLONG_MAX, 1, false);
    arithmos_rational_from_ull(&r2, 0, 1, false);
    overflow = arithmos_rational_difference(r1, r2, &result);
    assert(!overflow);

    arithmos_rational_from_ull(&r1, 3, 14, false);
    arithmos_rational_invert(&r1);
    ASSERT_RATIONAL_EQ(r1, 14, 3, false);
    arithmos_rational_from_ull(&r1, 5, 7, true);
    arithmos_rational_invert(&r1);
    ASSERT_RATIONAL_EQ(r1, 7, 5, true);
    arithmos_rational_from_ull(&r1, 0, 1, false);
    arithmos_rational_invert(&r1);
    ASSERT_RATIONAL_INF(r1, false);
    arithmos_rational_from_ull(&r1, 0, 1, true);
    arithmos_rational_invert(&r1);
    ASSERT_RATIONAL_INF(r1, true);
    r1 = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    arithmos_rational_invert(&r1);
    ASSERT_RATIONAL_EQ(r1, 0, 1, false);
    r1 = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    arithmos_rational_invert(&r1);
    ASSERT_RATIONAL_EQ(r1, 0, 1, true);
    r1 = ARITHMOS_RATIONAL_POSITIVE_NAN;
    arithmos_rational_invert(&r1);
    ASSERT_RATIONAL_NAN(r1, false);
    arithmos_rational_from_ull(&r1, ULLONG_MAX, 1, false);
    arithmos_rational_invert(&r1);
    ASSERT_RATIONAL_EQ(r1, 1, ULLONG_MAX, false);
    arithmos_rational_from_ull(&r1, 9, 2, true);
    arithmos_rational_invert(&r1);
    arithmos_rational_invert(&r1);
    ASSERT_RATIONAL_EQ(r1, 9, 2, true);

    arithmos_rational_from_ull(&r1, 2, 3, false);
    arithmos_rational_from_ull(&r2, 3, 4, false);
    overflow = arithmos_rational_product(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 1, 2, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 2, 3, false);
    arithmos_rational_from_ull(&r2, 3, 4, true);
    overflow = arithmos_rational_product(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 1, 2, true);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 2, 3, true);
    arithmos_rational_from_ull(&r2, 3, 4, true);
    overflow = arithmos_rational_product(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 1, 2, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 0, false); 
    arithmos_rational_from_ull(&r2, 5, 7, false);
    overflow = arithmos_rational_product(r1, r2, &result);
    ASSERT_RATIONAL_INF(result, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 0, true);
    arithmos_rational_from_ull(&r2, 5, 7, false);
    overflow = arithmos_rational_product(r1, r2, &result);
    ASSERT_RATIONAL_INF(result, true);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 0, false);
    overflow = arithmos_rational_product(r1, r1, &result);
    ASSERT_RATIONAL_INF(result, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 0, false);
    arithmos_rational_from_ull(&r2, 1, 0, true);
    overflow = arithmos_rational_product(r1, r2, &result);
    ASSERT_RATIONAL_INF(result, true);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 0, 0, false);
    arithmos_rational_from_ull(&r2, 1, 2, false);
    overflow = arithmos_rational_product(r1, r2, &result);
    ASSERT_RATIONAL_NAN(result, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, ULLONG_MAX, 1, false);
    arithmos_rational_from_ull(&r2, 2, 1, false);
    overflow = arithmos_rational_product(r1, r2, &result);
    assert(overflow);

    arithmos_rational_from_ull(&r1, 2, 3, false);
    arithmos_rational_from_ull(&r2, 4, 3, false);
    overflow = arithmos_rational_quotient(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 1, 2, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 2, 3, false);
    arithmos_rational_from_ull(&r2, 4, 3, true);
    overflow = arithmos_rational_quotient(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 1, 2, true);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 5, 2, true);
    arithmos_rational_from_ull(&r2, 1, 3, false);
    overflow = arithmos_rational_quotient(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 15, 2, true);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 3, false);
    arithmos_rational_from_ull(&r2, 0, 1, false);
    overflow = arithmos_rational_quotient(r1, r2, &result);
    ASSERT_RATIONAL_INF(result, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 0, 1, false);
    arithmos_rational_from_ull(&r2, 5, 4, false);
    overflow = arithmos_rational_quotient(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 0, 1, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 1, 0, false);
    arithmos_rational_from_ull(&r2, 1, 2, false);
    overflow = arithmos_rational_quotient(r1, r2, &result);
    ASSERT_RATIONAL_INF(result, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 3, 5, false);
    arithmos_rational_from_ull(&r2, 1, 0, false);
    overflow = arithmos_rational_quotient(r1, r2, &result);
    ASSERT_RATIONAL_EQ(result, 0, 1, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, 0, 0, false);
    arithmos_rational_from_ull(&r2, 1, 2, false);
    overflow = arithmos_rational_quotient(r1, r2, &result);
    ASSERT_RATIONAL_NAN(result, false);
    assert(!overflow);
    arithmos_rational_from_ull(&r1, ULLONG_MAX, 1, false);
    arithmos_rational_from_ull(&r2, 1, 2, false);
    overflow = arithmos_rational_quotient(r1, r2, &result);
    assert(overflow);

    Arithmos_Rational base;

    base = ARITHMOS_RATIONAL_POSITIVE_ZERO;
    overflow = arithmos_rational_power(&base, 0);
    assert(overflow == false);
    ASSERT_RATIONAL_EQ(base, 1, 1, false);
    base = ARITHMOS_RATIONAL_NEGATIVE_ZERO;
    overflow = arithmos_rational_power(&base, 0);
    assert(overflow == false);
    ASSERT_RATIONAL_EQ(base, 1, 1, false);
    base = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    overflow = arithmos_rational_power(&base, 0);
    assert(overflow == false);
    ASSERT_RATIONAL_NAN(base, false);
    base = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    overflow = arithmos_rational_power(&base, 0);
    assert(overflow == false);
    ASSERT_RATIONAL_NAN(base, false);
    base = ARITHMOS_RATIONAL_POSITIVE_NAN;
    overflow = arithmos_rational_power(&base, 10);
    assert(overflow == false);
    ASSERT_RATIONAL_NAN(base, false);
    base = ARITHMOS_RATIONAL_NEGATIVE_NAN;
    overflow = arithmos_rational_power(&base, 12345);
    assert(overflow == false);
    ASSERT_RATIONAL_NAN(base, false);
    arithmos_rational_from_ull(&base, 3, 4, false);
    overflow = arithmos_rational_power(&base, 0);
    assert(overflow == false);
    ASSERT_RATIONAL_EQ(base, 1, 1, false);
    arithmos_rational_from_ull(&base, 3, 4, true);
    overflow = arithmos_rational_power(&base, 1);
    assert(overflow == false);
    ASSERT_RATIONAL_EQ(base, 3, 4, true);
    arithmos_rational_from_ull(&base, 3, 4, false);
    overflow = arithmos_rational_power(&base, 2);
    assert(overflow == false);
    ASSERT_RATIONAL_EQ(base, 9, 16, false);
    arithmos_rational_from_ull(&base, 3, 4, true);
    overflow = arithmos_rational_power(&base, 2);
    assert(overflow == false);
    ASSERT_RATIONAL_EQ(base, 9, 16, false);
    arithmos_rational_from_ull(&base, 3, 4, true);
    overflow = arithmos_rational_power(&base, 3);
    assert(overflow == false);
    ASSERT_RATIONAL_EQ(base, 27, 64, true);
    base = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    overflow = arithmos_rational_power(&base, 3);
    assert(overflow == false);
    ASSERT_RATIONAL_INF(base, false);
    base = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    overflow = arithmos_rational_power(&base, 2);
    assert(overflow == false);
    ASSERT_RATIONAL_INF(base, false);
    base = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    overflow = arithmos_rational_power(&base, 3);
    assert(overflow == false);
    ASSERT_RATIONAL_INF(base, true);
    base = ARITHMOS_RATIONAL_POSITIVE_ZERO;
    overflow = arithmos_rational_power(&base, 5);
    assert(overflow == false);
    ASSERT_RATIONAL_EQ(base, 0, 1, false);
    base = ARITHMOS_RATIONAL_NEGATIVE_ZERO;
    overflow = arithmos_rational_power(&base, 7);
    assert(overflow == false);
    ASSERT_RATIONAL_EQ(base, 0, 1, true);
    arithmos_rational_from_ull(&base, 1, ULLONG_MAX / 2, false);
    overflow = arithmos_rational_power(&base, 2);
    assert(overflow == true);

    float f;

    arithmos_rational_from_ull(&r, 3, 4, false);
    f = arithmos_rational_to_f(&r);
    assert(f == 0.75f);
    arithmos_rational_from_ull(&r, 2, 5, true);
    f = arithmos_rational_to_f(&r);
    assert(f == -0.4f);
    r = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    f = arithmos_rational_to_f(&r);
    assert(isinf(f) && !signbit(f));
    r = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    f = arithmos_rational_to_f(&r);
    assert(isinf(f) && signbit(f));
    r = ARITHMOS_RATIONAL_POSITIVE_NAN;
    f = arithmos_rational_to_f(&r);
    assert(isnan(f));
    r = ARITHMOS_RATIONAL_POSITIVE_ZERO;
    f = arithmos_rational_to_f(&r);
    assert(f == 0.0f && !signbit(f));
    arithmos_rational_from_ull(&r, 0, 7, true);
    f = arithmos_rational_to_f(&r);
    assert(f == 0.0f && signbit(f));

    double d;

    arithmos_rational_from_ull(&r, 3, 4, false);
    d = arithmos_rational_to_d(&r);
    assert(d == 0.75);
    arithmos_rational_from_ull(&r, 2, 5, true);
    d = arithmos_rational_to_d(&r);
    assert(d == -0.4);
    r = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    d = arithmos_rational_to_d(&r);
    assert(isinf(d) && !signbit(d));
    r = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    d = arithmos_rational_to_d(&r);
    assert(isinf(d) && signbit(d));
    r = ARITHMOS_RATIONAL_POSITIVE_NAN;
    d = arithmos_rational_to_d(&r);
    assert(isnan(d));
    r = ARITHMOS_RATIONAL_POSITIVE_ZERO;
    d = arithmos_rational_to_d(&r);
    assert(d == 0.0 && !signbit(d));
    arithmos_rational_from_ull(&r, 0, 7, true);
    d = arithmos_rational_to_d(&r);
    assert(f == 0.0 && signbit(d));

    long double ld;

    arithmos_rational_from_ull(&r, 3, 4, false);
    ld = arithmos_rational_to_ld(&r);
    assert(ld == 0.75L);
    arithmos_rational_from_ull(&r, 2, 5, true);
    ld = arithmos_rational_to_ld(&r);
    assert(ld == -0.4L);
    r = ARITHMOS_RATIONAL_POSITIVE_INFINITY;
    ld = arithmos_rational_to_ld(&r);
    assert(isinf(ld) && !signbit(ld));
    r = ARITHMOS_RATIONAL_NEGATIVE_INFINITY;
    ld = arithmos_rational_to_ld(&r);
    assert(isinf(ld) && signbit(ld));
    r = ARITHMOS_RATIONAL_POSITIVE_NAN;
    ld = arithmos_rational_to_ld(&r);
    assert(isnan(ld));
    r = ARITHMOS_RATIONAL_POSITIVE_ZERO;
    ld = arithmos_rational_to_ld(&r);
    assert(ld == 0.0L && !signbit(ld));
    arithmos_rational_from_ull(&r, 0, 7, true);
    ld = arithmos_rational_to_ld(&r);
    assert(ld == 0.0L && signbit(ld));

    return 0;
}
